
# [metadata] contains general metadata for the GAMS project
[metadata]
# the id of the project (eg.: hsa)
project_id = ""  

# The project creator (e.g. the prinicpal investigator)
creator = "" 

# Set this to the funder of the project. Will be added to each object metadata
funder = ""

# You might want to keep this value ("GAMS")
publisher = "GAMS"  

# Set the default license for the project. 
# Can be overriden in project.csv and datastream.csv for single objects/data streams
rights = "Creative Commons Attribution-NonCommercial 4.0 (http://creativecommons.org/licenses/by-nc/4.0/)"



[general]
# This address will be added to each SIP package
contact_email = ""

# Normally dsid is the full filename (with extension). Set to false to strip extension for dsid.
dsid_keep_extension = true

# debug, info, warning, error or critical
loglevel = "info"

# A list of filenames/filename patterns, which should be ignored when creating datastreams.csv
ds_ignore_files = ["*.log"]

# Set the format detector to be used. Leave this on the default detector unless for good reasons
# Allowed values: siegfried, magika, base (pythons built in mimetypes) Default is siegfried 
format_detector = ""

# Using remote XML resources is unsave and thus intercepted, which should not be a problem,
# because we provide a XML catalog with the most used schema files like TEI or LIDO.
# If you want to use custom schemas, these must be locally acessible ('file:///') or on a safe_xml_host.
# So add hosts, where your custom schemas are located to this list
safe_xml_hosts = [
    "gams.uni-graz.at"
]

# If you want to use a detector service like a FITS Server, set this to the URL
# Currently not used
format_detector_url = ""


