[projectmetadata]
# the sigle of the project (eg.: hsa)
project = ""
# The project creator (like in Dublin Core)
creator = ""
# This should normally be "Gams"
publisher = "Gams"
rights = "Creative Commons Attribution-NonCommercial 4.0 (https://creativecommons.org/licenses/by-nc/4.0/)"

[objectcsv]
# Normally dsid it the full filename (with extension). Set to false to strip extension for dsid.
dsid_keep_extension = true